//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП_МДК._03
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingForWorkingHours
    {
        public int NumberAccounting { get; set; }
        public int PersonnelNumberAccounting { get; set; }
        public int DaysAccounting { get; set; }
        public int DayCodeAccounting { get; set; }
        public int HoursAccounting { get; set; }
        public string MonthAccounting { get; set; }
    
        public virtual DayCode DayCode { get; set; }
        public virtual Month Month { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
