//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП_МДК._03
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD : DbContext
    {
        private static BD _context;

        public BD()
            : base("name=BD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        internal static BD GetContext()
        {
            if (_context == null)
                _context = new BD();
            return _context;
        }


        public virtual DbSet<AbsentForAReason> AbsentForAReason { get; set; }
        public virtual DbSet<AccountingForWorkingHours> AccountingForWorkingHours { get; set; }
        public virtual DbSet<DataForPayroll> DataForPayroll { get; set; }
        public virtual DbSet<DayCode> DayCode { get; set; }
        public virtual DbSet<Decryption> Decryption { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<HoursMonthlySummary> HoursMonthlySummary { get; set; }
        public virtual DbSet<Month> Month { get; set; }
        public virtual DbSet<OffsettingAccount> OffsettingAccount { get; set; }
        public virtual DbSet<PaymentTypeCode> PaymentTypeCode { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
