//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП_МДК._03
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataForPayroll
    {
        public int NumberSalary { get; set; }
        public int PersonnelNumberSalary { get; set; }
        public int PaymentTypeCodeSalary { get; set; }
        public int OffsettingAccountSalary { get; set; }
        public int MonthSalary { get; set; }
        public int DaysSalary { get; set; }
        public int HoursSalary { get; set; }
    
        public virtual HoursMonthlySummary HoursMonthlySummary { get; set; }
        public virtual OffsettingAccount OffsettingAccount { get; set; }
        public virtual PaymentTypeCode PaymentTypeCode { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
