//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП_МДК._03
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoursMonthlySummary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoursMonthlySummary()
        {
            this.DataForPayroll = new HashSet<DataForPayroll>();
        }
    
        public int NumberSum { get; set; }
        public int PersonnelNumberSum { get; set; }
        public string MonthSum { get; set; }
        public int SumDays { get; set; }
        public int SumHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataForPayroll> DataForPayroll { get; set; }
        public virtual Month Month { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
