//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП_МДК._03
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodaga
    {
        public Nullable<int> tabl_nomer { get; set; }
        public int id_tovar { get; set; }
        public Nullable<System.DateTime> data_zakaza { get; set; }
        public string id_klient { get; set; }
        public Nullable<int> kolvo { get; set; }
    }
}
