//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП_МДК._03
{
    using System;
    using System.Collections.Generic;
    
    public partial class sotrudniki
    {
        public int tabl_nomer { get; set; }
        public string fio { get; set; }
        public string id_dolgnost { get; set; }
    }
}
