//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП_МДК._03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.AbsentForAReason = new HashSet<AbsentForAReason>();
            this.AccountingForWorkingHours = new HashSet<AccountingForWorkingHours>();
            this.DataForPayroll = new HashSet<DataForPayroll>();
            this.HoursMonthlySummary = new HashSet<HoursMonthlySummary>();
        }
    
        public int PersonnelNumber { get; set; }
        public string Initials { get; set; }
        public string DecryptionStaff { get; set; }
        public string PositionStaff { get; set; }
        public string DepartmentStaff { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbsentForAReason> AbsentForAReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingForWorkingHours> AccountingForWorkingHours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataForPayroll> DataForPayroll { get; set; }
        public virtual Decryption Decryption { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoursMonthlySummary> HoursMonthlySummary { get; set; }
    }
}
