//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП_МДК._03
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovar
    {
        public int id_tovar { get; set; }
        public string name { get; set; }
        public string cena { get; set; }
        public string kol_vo { get; set; }
        public string ekran { get; set; }
        public string ves { get; set; }
        public string procesor { get; set; }
        public string ozy { get; set; }
        public string pamat { get; set; }
        public string batarea { get; set; }
        public string camera { get; set; }
    }
}
