//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace КП_МДК._03
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserNumber { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FIOUser { get; set; }
        public string RoleUser { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
